program test
    
    !     Driver for DNSQ example.

      INTEGER J,IOPT,N,MAXFEV,ML,MU,MODE,NPRINT,INFO,NFEV,LDFJAC,LR,NWRITE
      DOUBLE PRECISION XTOL,EPSFCN,FACTOR,FNORM
      DOUBLE PRECISION X(9),FVEC(9),DIAG(9),FJAC(9,9),R(45),QTF(9), &
         WA1(9),WA2(9),WA3(9),WA4(9)
      DOUBLE PRECISION DENORM,D1MACH
      EXTERNAL FCN, JAC
      DATA NWRITE /6/

      IOPT = 2
      N = 9

!     THE FOLLOWING STARTING VALUES PROVIDE A ROUGH SOLUTION.

      DO 10 J = 1, 9
         X(J) = -1.E0
   10    CONTINUE

      LDFJAC = 9
      LR = 45

!     SET XTOL TO THE SQUARE ROOT OF THE MACHINE PRECISION.
!     UNLESS HIGH PRECISION SOLUTIONS ARE REQUIRED,
!     THIS IS THE RECOMMENDED SETTING.

      XTOL = SQRT(D1MACH(4))

      MAXFEV = 2000
      ML = 1
      MU = 1
      EPSFCN = 0.E0
      MODE = 2
      DO 20 J = 1, 9
         DIAG(J) = 1.E0
   20    CONTINUE
      FACTOR = 1.E2
      NPRINT = 0

      CALL DNSQ(FCN,JAC,IOPT,N,X,FVEC,FJAC,LDFJAC,XTOL,MAXFEV,ML,MU, &
                EPSFCN,DIAG,MODE,FACTOR,NPRINT,INFO,NFEV,NJEV, &
                R,LR,QTF,WA1,WA2,WA3,WA4)
      FNORM = DENORM(N,FVEC)
      WRITE (NWRITE,1000) FNORM,NFEV,INFO,(X(J),J=1,N)
      STOP
 1000 FORMAT (5X,' FINAL L2 NORM OF THE RESIDUALS',E15.7 // &
             5X,' NUMBER OF FUNCTION EVALUATIONS',I10 // & 
             5X,' EXIT PARAMETER',16X,I10 // &
             5X,' FINAL APPROXIMATE SOLUTION' // (5X,3E15.7))
      
    
end program test
    
    
    