language: shell

os:
  - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed but can no longer be installed with
# sudo apt-get.
addons:
  apt:
    packages:
      - gfortran
      - cmake
      - libgomp1
  artifacts:
    s3_region: "eu-west-2"
    paths: $HOME/AllBuildFiles.tar.gz

env:
  global:
    - secure: "TYAJB6kLFTqLzFJx44zHMyhNEKJ8i2PvTLlKuft5jsoN+d/OCxqBS847A920vd1N8MMlnBfa/jjm2fB3NjbBE7sIg0pQwh1OuYTkSPVUNQvSfBHz/aodnJmnctaUlXvO6Je7W276C+kikzBicKB1j9Q2v/roBj4aJmXbaR0dP0Hc6x4Fzw6pPbc9ya4Ftrt14X0EXMPydzB+6wjNEi0bZI48+xrefdBrq7Nb3aMkrvpQ9XpNrzegvn9Z8DZxnGCwGdCHv+wYbzydxD/ROzgRkn4ycE26+boq5hSA1MyoQUsZqzNNDyZei6znuqNMBLDRiHZ7CzwiXDl4xVtcuf4hQ87pvQFM7Z6CYDJbN4aIZAQESu7kC1/gU/N2muBnG6lU+WjrDoQTZWdygB5ALH9s209+yL/yrZqaeuWaPPK54TF1CnGICE1VYkdReth5eHTfCYrKegz4zJlgCK3nXB+/voJWqdF5c0IHWi1Q0p8v35/J0wWnVgWevWAPaSS2Cu9Qs+TMI9hjA2zFYIUfwJU/lA7fgCctYFvgSS30G7PuqfC9l2N5qrrWt+TFw+4tDQzhcpbWaosd8p40LzkbtdR0sC3XB2G65X5xG9MpyLihuYLQFypMqWsRh39kqCUdluujF2Xo9/2IjHwZ6aC3ZCpY46D+Rvm2JH/0VeFjt6DNYNM="
    - secure: "Hp/WmhjO9EtYMVMoHtP3LXvB4EX0EgdAoUctediRXCdFWTk004VaFYJuSXoGLBucl+qTeEVt78Y2TFCbAgn7u/Y5BPuqkc3qoq/OeyhX1fXsw8/f/sCfb00aUm9qFxHDwWeu9jmMfVVvwEXlZHzxmdHt4SHv3jMNmsQMCfb1iTzAZwlnsCyBFJNTAGFXjvpp9ljs6KGM/AGlECoBkWfE/PY6MAQ/5wj8ZXuduABJMP0Tbx3gyJfspawSktIve8MvggLIPQFQmxrkA8DE0P6WGHbP6dDIhV0zWwQTAHOGjsCBjEfhKtqSAw9J6Z+a0ByDj8QRZfduOVP73AmJ/6tkIiSQcpWCXE5CW0RAUYOyb4iAhnPmCuxwAmxcUy9w/I59U3oPENHmeObh4YxeimFdVxJLDhWKbi+smV9DsKOYl9Wt5bSyeN0TT+y5lfEsETR100slS6qAo6YZgpSuW36ot5WjE4DlBpFdRYmXQ0FYfN7ayAehzNPOzQje62U9cCIMIuv4JBLJnT42thxTxatpIQuHyhrqhfnRmWMLpCml+66lZNRzUHAe1uH52yMPGKyhW2GWpnvr2OxgvNe3/qxalOq1WnpdJ/SSJlAyJysyk4rZuG9K8UTfHhTNxbAxUg1wVvsS3al65IgnfMqTiPwcA3UXHzsrsahbA1jKzBzmyfA="
    - secure: "KwGwZ87OUUq7VZmqNjXzrLhTcGEBdax9fdLAUIc78y7IYVIrPJxOU7hgyOZY6OaNdJqxuBBrlb1IbLOSmrMW89XjpBkB2VVcL0iGeYCRWzGynMQ8a7L3VOCF68vIV5xxVUnkbPugtcKemkfcoemocm8PCaQM6RrcUfvgWxpvaAq3884EMM4d+DA+wVfyBDrvzJLPjPlZsHoJT+8FAUOXVJLRgy2TJlXAJamnGU6g/4s2BYU1vxQglJSNfcgOt0/T4PyowTwLascFN2VCF4TbcXDIbAt0CRee0Oxvq3WEw8/55SUkCI/hrJj9KytIOW5mVc86QPtuQUpDnMrem+xjraAkLDd8taMnDcyt39dw+KgsaovAF0ARG89QZ0j49Tn/cnqNvYWrFTBcSzFmGcc83BvLorjXkPLxh0QyzL810w1inE9Hze3ZZoV9dbLTI5RssnyKJwaSmRs+Ha8x50QIw71zTG1zFTBD1Q4oHDzKzh7yUe1f3XEyySWUHiP5ZVXLOhwhgnXUMsh+fPPCLDfN+GrBv4SYCQ4Ijb831msZFz4sJWhAJsfhL6BAkdU49TB+zD5iLWH2sZtlR7hfID0tslLKfF8UMLp+iK93AaI8/mbmfgzI3n4l3Q/PEcdPqbVOnjclo9aqBLFim0nnQH7KyJK6ugXffD6Ubgkmwvh5w6I="

matrix:
  # Don't wait for allowed failures - do we really need this? TODO
  fast_finish: true

  include:
    - os: osx
      addons:
        homebrew:
          packages: &osx_sources
            - llvm
            - libomp
          update: true
      env:
        - TITLE="OSX - GFortran"
      
    - os: linux
      env:
        - TITLE="Linux - GFortran"

    - os: linux
      env:
        - TITLE="Linux - IFort"
      addons:
        apt:
          sources:
          - sourceline: 'deb https://apt.repos.intel.com/oneapi all main'
            key_url: 'https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB'
          packages:
          - intel-oneapi-ifort
      install:
        - source /opt/intel/inteloneapi/compiler/latest/env/vars.sh

    - os: windows
      env:
        - TITLE="Windows (MinGW64) - GFortran"

before_install:
  # Install stuff specifically for MacOS
  - if [ $TRAVIS_OS_NAME = osx ]; then brew link gcc; fi
  # Install stuff specifically for Windows
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install make; fi

install:

before_script:

script:
  - cd FortranCode
  - mkdir build
  - cd build
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -Ddoopenmp=OFF
  - make -j
  # - ctest --output-on-failure
  # - ctest -L fast --output-on-failure
  - travis_wait 30 ctest -L "(fast|medium)" --output-on-failure

after_script:
  - find . -name "uninstal*"
  - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'
  - cd "${HOME}"
  - tar cvfz AllBuildFiles.tar.gz *.*

after_success:

