language: python

os:
  - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed but can no longer be installed with
# sudo apt-get.
addons:
  apt:
    packages:
      - gfortran
      - cmake
      - libgomp1

matrix:
  # Don't wait for allowed failures - do we really need this? TODO
  fast_finish: true

  include:
    - os: osx
      language: generic
      
    - os: linux
      language: generic

    - os: windows
      language: generic

before_install:
  # Install stuff specifically for MacOS
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; rm '/usr/local/include/c++'; brew install gcc; fi

install:

before_script:

script:
  - cd FortranCode
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -Ddoopenmp=OFF
  - make -j
  - while sleep 540 ; do echo "=========== tests are taking more than 9m - pinging travis =========="; done &
#  - ctest --output-on-failure
  - ctest -L fast --output-on-failure
#  - ctest -L "(fast|medium)" --output-on-failure

after_success:

