function outResid = StdSttKineticsResidual(beta,Temp,Pres,...
    EnrgGasSpecies,yO2,yNO2,yNO,...
    ApreO2ads,PERatioO2adsdes,EaO2ads,DEadsO,ProxFacO2ads,...
    ApreNOoxi,PERatioNOoxiNO2red,EaNOoxi,ProxFacNOoxi,...
    H0,H1,...
    STheta,h,nn,ZPEO,QvibO,ApproxIdent,...
    CorrelLHS,CorrelRHS,nsites,muOstarguess,gcguess,options)

options = optimoptions('fsolve',...
    'Display','off');
        
[PFcn,gcsolnT,muOstar,CorrelOccup,CorrelUnocc, ...
    AvgekO2ads,AvgekO2des,AvgekNOoxi,AvgekNO2re] = ...
    SolveForMuCorrelRatesExtd(beta,Temp,...
    EnrgGasSpecies,EaO2ads,DEadsO,ProxFacO2ads,...
    EaNOoxi,ProxFacNOoxi,...
    H0,H1,...
    STheta,h,nn,ZPEO,QvibO,ApproxIdent,...
    CorrelLHS,CorrelRHS,nsites,muOstarguess,gcguess,options);

RNOoxi = ApreNOoxi*yNO*Pres*AvgekNOoxi.*STheta;
RNO2re = ApreNOoxi/PERatioNOoxiNO2red*yNO2*Pres*AvgekNO2re.*(1-STheta);
RO2ads = 2*nn*ApreO2ads*yO2*Pres*AvgekO2ads.*CorrelUnocc;
RO2des = 2*nn*ApreO2ads/PERatioO2adsdes*AvgekO2des.*CorrelOccup;

NetRate = RNO2re-RNOoxi+RO2ads-RO2des;

outResid = log(RNO2re+RO2ads)-log(RNOoxi+RO2des) ;

return

end 